### ISSUE TITLE
[Keyboard Shortcuts] "Open the launcher" appears twice in search results

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-settings#1463]
<img width="579" height="359" alt="Image" src="https://github.com/user-attachments/assets/e9fa923a-5735-415c-9f82-1e0290057ba7" />

**Comment by KodeBarista** [comment]
Most probably this issue is fixed

<img width="711" height="350" alt="Image" src="https://github.com/user-attachments/assets/467fc638-d00b-450f-a05c-7d477b40067d" />

**Comment by leviport** [comment]
I'm still seeing two of them:
<img width="791" height="526" alt="Image" src="https://github.com/user-attachments/assets/53ff5117-adc5-4faa-8f56-a3708ac8885f" />

**Comment by KodeBarista** [comment]
Has it been fixed? I don't see it in Fedora COSMIC nightly.

<img height="295" alt="Image" src="https://github.com/user-attachments/assets/01ee0206-45b4-44ce-9c5e-39243be5d58f" />
