### ISSUE TITLE
[Input Devices > Keyboard] Cannot modify or delete keyboard shortcuts found via the search field

### ISSUE THREAD

**Issue by slackerbob** [pop-os/cosmic-settings#525]
Under Keyboard Shortcuts, after using the search field to find a keyboard shortcut, any modification (including delete) fails.

Steps to recreate:

1. Under Keyboard Shortcuts, enter "Terminal" into the search box.
2. Click the "Open a terminal" keyboard shortcut"
3. Click the Trashcan icon to delete the existing shortcut.
4. The window closes and the search results all disappear.

5. Entering anything into the search box results in the "Open the terminal" shortcut window re-appearing, unmodified.

**Comment by mmstick** [comment]
This seems to have been fixed a while back

**Comment by WatchMkr** [comment]
I'm still able to reproduce this. After searching for and the deleting the "Open a terminal" shortcut, searching for "terminal" again will still show "Super+T" is still the shortcut.
